# Generated by Django 3.2 on 2024-12-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0004_tournament_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerimage',
            name='tournament',
        ),
        migrations.AddField(
            model_name='bannerimage',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
    ]
