# Generated by Django 5.0 on 2025-01-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0006_staff_tournament_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='event_type',
            field=models.CharField(choices=[('ONLINE', 'Online Tournament'), ('OFFLINE', 'Offline Tournament'), ('HYBRID', 'Hybrid Tournament')], default='ONLINE', max_length=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player_structure',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('TAG_DUELING', 'Tag Dueling'), ('THREE_PLAYER_TEAM', 'Three-Player Team'), ('FOUR_PLAYER_TEAM', 'Four-Player Team'), ('FIVE_PLAYER_TEAM', 'Five-Player Team')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_structure',
            field=models.CharField(choices=[('SWISS_DRAW', 'Swiss Draw'), ('SINGLE_ELIMINATION', 'Single-Elimination')], default='SWISS_DRAW', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_style',
            field=models.CharField(choices=[('CONSTRUCTED_ADVANCED', 'Constructed - Advanced'), ('CONSTRUCTED_TRADITIONAL', 'Constructed - Traditional'), ('SEALED', 'Sealed'), ('OPEN_DUELING', 'Open Dueling')], default='CONSTRUCTED_ADVANCED', max_length=25),
        ),
    ]
