# Generated by Django 5.1.6 on 2025-02-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0007_tournament_event_type_tournament_player_structure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='first_prize',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='round_time',
            field=models.IntegerField(blank=True, help_text='Round time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='second_prize',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='third_prize',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
