# Generated by Django 5.1.6 on 2025-02-08 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0008_tournament_first_prize_tournament_round_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwissFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('match_date', models.DateTimeField()),
                ('start_time', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_tournament_completed', models.BooleanField(default=False)),
                ('participant1_score', models.IntegerField(default=0)),
                ('participant2_score', models.IntegerField(default=0)),
                ('nominated_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swiss_nominated_fixtures', to='Tournaments.participant')),
                ('participant1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swiss_fixture_participant1', to='Tournaments.participant')),
                ('participant2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swiss_fixture_participant2', to='Tournaments.participant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tournaments.tournament')),
                ('verified_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swiss_verified_fixtures', to='Tournaments.participant')),
            ],
        ),
    ]
