# Generated by Django 5.1.6 on 2025-02-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0009_swissfixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='swissfixture',
            name='draw',
            field=models.BooleanField(default=False),
        ),
    ]
